// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: prover.proto

package prover

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProofType int32

const (
	ProofType_NONE  ProofType = 0
	ProofType_EVM   ProofType = 1
	ProofType_STATE ProofType = 2
	ProofType_SUPER ProofType = 3
	ProofType_AGG   ProofType = 4
)

// Enum value maps for ProofType.
var (
	ProofType_name = map[int32]string{
		0: "NONE",
		1: "EVM",
		2: "STATE",
		3: "SUPER",
		4: "AGG",
	}
	ProofType_value = map[string]int32{
		"NONE":  0,
		"EVM":   1,
		"STATE": 2,
		"SUPER": 3,
		"AGG":   4,
	}
)

func (x ProofType) Enum() *ProofType {
	p := new(ProofType)
	*p = x
	return p
}

func (x ProofType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofType) Descriptor() protoreflect.EnumDescriptor {
	return file_prover_proto_enumTypes[0].Descriptor()
}

func (ProofType) Type() protoreflect.EnumType {
	return &file_prover_proto_enumTypes[0]
}

func (x ProofType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofType.Descriptor instead.
func (ProofType) EnumDescriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{0}
}

type ProveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceString string    `protobuf:"bytes,1,opt,name=trace_string,json=traceString,proto3" json:"trace_string,omitempty"`
	ProofType   ProofType `protobuf:"varint,2,opt,name=proof_type,json=proofType,proto3,enum=prover.ProofType" json:"proof_type,omitempty"`
}

func (x *ProveRequest) Reset() {
	*x = ProveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prover_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveRequest) ProtoMessage() {}

func (x *ProveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveRequest.ProtoReflect.Descriptor instead.
func (*ProveRequest) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{0}
}

func (x *ProveRequest) GetTraceString() string {
	if x != nil {
		return x.TraceString
	}
	return ""
}

func (x *ProveRequest) GetProofType() ProofType {
	if x != nil {
		return x.ProofType
	}
	return ProofType_NONE
}

type ProveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinalPair []byte `protobuf:"bytes,1,opt,name=final_pair,json=finalPair,proto3" json:"final_pair,omitempty"`
	Proof     []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *ProveResponse) Reset() {
	*x = ProveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prover_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveResponse) ProtoMessage() {}

func (x *ProveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveResponse.ProtoReflect.Descriptor instead.
func (*ProveResponse) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{1}
}

func (x *ProveResponse) GetFinalPair() []byte {
	if x != nil {
		return x.FinalPair
	}
	return nil
}

func (x *ProveResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type ProverSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProverSpecRequest) Reset() {
	*x = ProverSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prover_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProverSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProverSpecRequest) ProtoMessage() {}

func (x *ProverSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProverSpecRequest.ProtoReflect.Descriptor instead.
func (*ProverSpecRequest) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{2}
}

type ProverSpecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProofTypeDesc string `protobuf:"bytes,1,opt,name=proof_type_desc,json=proofTypeDesc,proto3" json:"proof_type_desc,omitempty"`
	Degree        uint32 `protobuf:"varint,2,opt,name=degree,proto3" json:"degree,omitempty"`
	AggDegree     uint32 `protobuf:"varint,3,opt,name=agg_degree,json=aggDegree,proto3" json:"agg_degree,omitempty"`
	ChainId       uint32 `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MaxTxs        uint32 `protobuf:"varint,5,opt,name=max_txs,json=maxTxs,proto3" json:"max_txs,omitempty"`
	MaxCallData   uint32 `protobuf:"varint,6,opt,name=max_call_data,json=maxCallData,proto3" json:"max_call_data,omitempty"`
}

func (x *ProverSpecResponse) Reset() {
	*x = ProverSpecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prover_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProverSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProverSpecResponse) ProtoMessage() {}

func (x *ProverSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProverSpecResponse.ProtoReflect.Descriptor instead.
func (*ProverSpecResponse) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{3}
}

func (x *ProverSpecResponse) GetProofTypeDesc() string {
	if x != nil {
		return x.ProofTypeDesc
	}
	return ""
}

func (x *ProverSpecResponse) GetDegree() uint32 {
	if x != nil {
		return x.Degree
	}
	return 0
}

func (x *ProverSpecResponse) GetAggDegree() uint32 {
	if x != nil {
		return x.AggDegree
	}
	return 0
}

func (x *ProverSpecResponse) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ProverSpecResponse) GetMaxTxs() uint32 {
	if x != nil {
		return x.MaxTxs
	}
	return 0
}

func (x *ProverSpecResponse) GetMaxCallData() uint32 {
	if x != nil {
		return x.MaxCallData
	}
	return 0
}

var File_prover_proto protoreflect.FileDescriptor

var file_prover_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x30, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x54, 0x79, 0x70, 0x65, 0x22, 0x44, 0x0a, 0x0d, 0x50,
	0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xcb, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x76, 0x65,
	0x72, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a,
	0x0f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x54, 0x79, 0x70,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x67, 0x67, 0x5f, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x61, 0x67, 0x67, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x74,
	0x78, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x54, 0x78, 0x73,
	0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x43, 0x61, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x2a, 0x3d, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45,
	0x56, 0x4d, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x55, 0x50, 0x45, 0x52, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x47,
	0x47, 0x10, 0x04, 0x32, 0x7d, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x34, 0x0a,
	0x05, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prover_proto_rawDescOnce sync.Once
	file_prover_proto_rawDescData = file_prover_proto_rawDesc
)

func file_prover_proto_rawDescGZIP() []byte {
	file_prover_proto_rawDescOnce.Do(func() {
		file_prover_proto_rawDescData = protoimpl.X.CompressGZIP(file_prover_proto_rawDescData)
	})
	return file_prover_proto_rawDescData
}

var file_prover_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_prover_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_prover_proto_goTypes = []interface{}{
	(ProofType)(0),             // 0: prover.ProofType
	(*ProveRequest)(nil),       // 1: prover.ProveRequest
	(*ProveResponse)(nil),      // 2: prover.ProveResponse
	(*ProverSpecRequest)(nil),  // 3: prover.ProverSpecRequest
	(*ProverSpecResponse)(nil), // 4: prover.ProverSpecResponse
}
var file_prover_proto_depIdxs = []int32{
	0, // 0: prover.ProveRequest.proof_type:type_name -> prover.ProofType
	1, // 1: prover.Prover.Prove:input_type -> prover.ProveRequest
	3, // 2: prover.Prover.Spec:input_type -> prover.ProverSpecRequest
	2, // 3: prover.Prover.Prove:output_type -> prover.ProveResponse
	4, // 4: prover.Prover.Spec:output_type -> prover.ProverSpecResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prover_proto_init() }
func file_prover_proto_init() {
	if File_prover_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prover_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prover_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prover_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProverSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prover_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProverSpecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prover_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prover_proto_goTypes,
		DependencyIndexes: file_prover_proto_depIdxs,
		EnumInfos:         file_prover_proto_enumTypes,
		MessageInfos:      file_prover_proto_msgTypes,
	}.Build()
	File_prover_proto = out.File
	file_prover_proto_rawDesc = nil
	file_prover_proto_goTypes = nil
	file_prover_proto_depIdxs = nil
}
